apiVersion: v1
kind: Template
labels:
  app: subatomic-jenkins
  template: jenkins-persistent-subatomic-template
metadata:
  annotations:
    description: |-
      Jenkins service, with persistent storage.

      NOTE: This is a Subatomic managed resource. Please refer to the Subatomic documentation for more information
    iconClass: icon-jenkins
    openshift.io/display-name: Jenkins [Subatomic]
    openshift.io/documentation-url: https://subatomic.bison.ninja/teams/cicd
    openshift.io/provider-display-name: Subatomic
    openshift.io/support-url: https://subatomic.bison.ninja
    subatomic/version: '2.1'
    tags: jenkins
  name: jenkins-persistent-subatomic
objects:
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
    name: jenkins
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: jenkins
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: jenkins
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: 'true'
    name: jenkins
  spec:
    replicas: 1
    selector:
      name: jenkins
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: jenkins
      spec:
        containers:
          - name: jenkins  
            image: ' '            
            env:
              - name: OPENSHIFT_ENABLE_OAUTH
                value: 'true'
              - name: BITBUCKET_URL
                value: ${BITBUCKET_URL}
              - name: BITBUCKET_NAME
                value: ${BITBUCKET_NAME}
              - name: BITBUCKET_CREDENTIALS_ID
                value: ${BITBUCKET_CREDENTIALS_ID}
              - name: JENKINS_ADMIN_EMAIL
                value: ${JENKINS_ADMIN_EMAIL}                
              - name: MAVEN_SLAVE_IMAGE
                value: "${DEVOPS_URL}/${MAVEN_SLAVE_IMAGE}"                
              - name: NODEJS_SLAVE_IMAGE
                value: "${DEVOPS_URL}/${NODEJS_SLAVE_IMAGE}"           
              - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
                value: 'true'
              - name: KUBERNETES_MASTER
                value: https://kubernetes.default:443
              - name: KUBERNETES_TRUST_CERTIFICATES
                value: 'true'
              - name: JENKINS_SERVICE_NAME
                value: jenkins
              - name: JNLP_SERVICE_NAME
                value: jenkins-jnlp
              - name: OPENSHIFT_JENKINS_JVM_ARCH
                value: x86_64
            livenessProbe:
              failureThreshold: 30
              httpGet:
                path: /login
                port: 8080
              initialDelaySeconds: 30
              timeoutSeconds: 3
            readinessProbe:
              httpGet:
                path: /login
                port: 8080
              initialDelaySeconds: 30
              timeoutSeconds: 3
            resources:
              limits:
                memory: ${MEMORY_LIMIT}
            volumeMounts:
              - mountPath: /var/lib/jenkins
                name: jenkins-data
        restartPolicy: Always
        serviceAccountName: jenkins
        volumes:
          - name: jenkins-data
            persistentVolumeClaim:
              claimName: jenkins
    triggers:
      - imageChangeParams:
          automatic: true
          containerNames:
            - jenkins
          from:
            kind: ImageStreamTag
            name: ${JENKINS_IMAGE_STREAM_TAG}
            namespace: ${NAMESPACE}
        type: ImageChange
      - type: ConfigChange
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference",
      "apiVersion":"v1","reference":{"kind":"Route","name":"jenkins"}}'
    name: jenkins
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    name: jenkins_edit
  roleRef:
    name: edit
  subjects:
    - kind: ServiceAccount
      name: jenkins
- apiVersion: v1
  kind: Service
  metadata:
    name: jenkins-jnlp
  spec:
    ports:
      - name: agent
        nodePort: 0
        port: 50000
        protocol: TCP
        targetPort: 50000
    selector:
      name: jenkins
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/dependencies: '[{"name": "jenkins-jnlp",
        "namespace": "", "kind": "Service"}]'
      service.openshift.io/infrastructure: 'true'
    name: jenkins
  spec:
    ports:
      - name: web
        nodePort: 0
        port: 80
        protocol: TCP
        targetPort: 8080
    selector:
      name: jenkins
parameters:
- displayName: Bitbucket URL
  name: BITBUCKET_URL
  required: true
- displayName: Bitbucket instance name
  name: BITBUCKET_NAME
  required: true
- description: This credential Id value must match the Id of the credential that will be used to conenct to the Bitbucket instance.
  displayName: Bitbucket credential Id
  name: BITBUCKET_CREDENTIALS_ID
  required: true
- displayName: Admin email address for Jenkins originating mails
  name: JENKINS_ADMIN_EMAIL
  required: true
- description: This Jenkins slave image can be used to build Maven based projects
  displayName: The Subatomic Maven slave image
  name: MAVEN_SLAVE_IMAGE
  required: false
  value: jenkins-slave-maven-subatomic:2.0
- description: This Jenkins slave image can be used to build Node based projects
  displayName: The Subatomic Node slave image
  name: NODEJS_SLAVE_IMAGE
  required: false
  value: jenkins-slave-nodejs-subatomic:2.0
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  value: 1024Mi
- description: Volume space available for data, e.g. 512Mi, 2Gi.
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi
- description: The OpenShift Namespace where the Jenkins ImageStream resides.
  displayName: Jenkins ImageStream Namespace
  name: NAMESPACE
- description: Name of the ImageStreamTag to be used for the Jenkins image.
  displayName: Jenkins ImageStreamTag
  name: JENKINS_IMAGE_STREAM_TAG
  value: jenkins-subatomic:2.1
- description: Url to the devops environment which holds the slave images
  displayName: Devops Url
  name: DEVOPS_URL
  required: true