<?xml version='1.0' encoding='UTF-8'?>
<hudson>
  <disabledAdministrativeMonitors/>
  <version>2.89.2</version>
  <numExecutors>5</numExecutors>
  <mode>NORMAL</mode>
  <useSecurity>true</useSecurity>
  <authorizationStrategy class="hudson.security.GlobalMatrixAuthorizationStrategy">
    <permission>hudson.model.Computer.Configure:admin</permission>
    <permission>hudson.model.Computer.Delete:admin</permission>
    <permission>hudson.model.Hudson.Administer:admin</permission>
    <permission>hudson.model.Hudson.Read:admin</permission>
    <permission>hudson.model.Item.Build:admin</permission>
    <permission>hudson.model.Item.Configure:admin</permission>
    <permission>hudson.model.Item.Create:admin</permission>
    <permission>hudson.model.Item.Delete:admin</permission>
    <permission>hudson.model.Item.Read:admin</permission>
    <permission>hudson.model.Item.Workspace:admin</permission>
    <permission>hudson.model.Run.Delete:admin</permission>
    <permission>hudson.model.Run.Update:admin</permission>
    <permission>hudson.model.View.Configure:admin</permission>
    <permission>hudson.model.View.Create:admin</permission>
    <permission>hudson.model.View.Delete:admin</permission>
    <permission>hudson.scm.SCM.Tag:admin</permission>
  </authorizationStrategy>
  <securityRealm class="hudson.security.HudsonPrivateSecurityRealm">
    <disableSignup>true</disableSignup>
    <enableCaptcha>false</enableCaptcha>
  </securityRealm>
  <disableRememberMe>false</disableRememberMe>
  <workspaceDir>${ITEM_ROOTDIR}/workspace</workspaceDir>
  <buildsDir>${ITEM_ROOTDIR}/builds</buildsDir>
  <markupFormatter class="org.jenkins_ci.plugins.pegdown_formatter.PegDownFormatter" plugin="pegdown-formatter@1.3">
    <flags>262399</flags>
    <extensions>
      <org.jenkins__ci.plugins.pegdown__formatter.PegDownExtension>
        <name>SUPPRESS_ALL_HTML</name>
        <flag>196608</flag>
        <selected>false</selected>
      </org.jenkins__ci.plugins.pegdown__formatter.PegDownExtension>
    </extensions>
    <advancedExtensions>
      <org.jenkins__ci.plugins.pegdown__formatter.PegDownExtension>
        <name>ABBREVIATIONS</name>
        <flag>4</flag>
        <selected>true</selected>
      </org.jenkins__ci.plugins.pegdown__formatter.PegDownExtension>
      <org.jenkins__ci.plugins.pegdown__formatter.PegDownExtension>
        <name>AUTOLINKS</name>
        <flag>16</flag>
        <selected>true</selected>
      </org.jenkins__ci.plugins.pegdown__formatter.PegDownExtension>
      <org.jenkins__ci.plugins.pegdown__formatter.PegDownExtension>
        <name>DEFINITIONS</name>
        <flag>64</flag>
        <selected>true</selected>
      </org.jenkins__ci.plugins.pegdown__formatter.PegDownExtension>
      <org.jenkins__ci.plugins.pegdown__formatter.PegDownExtension>
        <name>FENCED_CODE_BLOCKS</name>
        <flag>128</flag>
        <selected>true</selected>
      </org.jenkins__ci.plugins.pegdown__formatter.PegDownExtension>
      <org.jenkins__ci.plugins.pegdown__formatter.PegDownExtension>
        <name>HARDWRAPS</name>
        <flag>8</flag>
        <selected>true</selected>
      </org.jenkins__ci.plugins.pegdown__formatter.PegDownExtension>
      <org.jenkins__ci.plugins.pegdown__formatter.PegDownExtension>
        <name>NO_FOLLOW_LINKS</name>
        <flag>262144</flag>
        <selected>true</selected>
      </org.jenkins__ci.plugins.pegdown__formatter.PegDownExtension>
      <org.jenkins__ci.plugins.pegdown__formatter.PegDownExtension>
        <name>SMARTYPANTS</name>
        <flag>3</flag>
        <selected>true</selected>
      </org.jenkins__ci.plugins.pegdown__formatter.PegDownExtension>
      <org.jenkins__ci.plugins.pegdown__formatter.PegDownExtension>
        <name>TABLES</name>
        <flag>32</flag>
        <selected>true</selected>
      </org.jenkins__ci.plugins.pegdown__formatter.PegDownExtension>
    </advancedExtensions>
  </markupFormatter>
  <jdks/>
  <viewsTabBar class="hudson.views.DefaultViewsTabBar"/>
  <myViewsTabBar class="hudson.views.DefaultMyViewsTabBar"/>
  <clouds>
    ${KUBERNETES_CONFIG}
  </clouds>
  <quietPeriod>1</quietPeriod>
  <scmCheckoutRetryCount>0</scmCheckoutRetryCount>
  <views>
    <hudson.model.AllView>
      <owner class="hudson" reference="../../.."/>
      <name>All</name>
      <filterExecutors>false</filterExecutors>
      <filterQueue>false</filterQueue>
      <properties/>
    </hudson.model.AllView>
  </views>
  <primaryView>All</primaryView>
  <slaveAgentPort>${JNLP_PORT}</slaveAgentPort>
  <disabledAgentProtocols>
    <string>JNLP-connect</string>
    <string>JNLP2-connect</string>
  </disabledAgentProtocols>
  <label>master</label>
  <nodeProperties/>
  <globalNodeProperties/>
  <noUsageStatistics>true</noUsageStatistics>
</hudson>